/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wishlist2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*WishList2GUI.java
 * *date 10/01/22
 * @author John Ringrose
 */
public class WishList2GUI extends javax.swing.JFrame {

    /**
     * Creates new form WishList2GUI
     */
     public ArrayList<WishList2> WishLists;
    public WishList2GUI() {
        WishLists = new ArrayList<>();
        initComponents();
        //setting the additional options to invisible till selected
         brandLBL.setVisible(false);
        brandTF.setVisible(false);
        colourLBL.setVisible(false);
        colourTF.setVisible(false);
        sportLBL.setVisible(false);
        sportTF.setVisible(false);
        typeLBL.setVisible(false);
        typeTF.setVisible(false);
        makeLBL.setVisible(false);
        makeTF.setVisible(false);
        modelLBL.setVisible(false);
        modelTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGrp = new javax.swing.ButtonGroup();
        descriptionLBL = new javax.swing.JLabel();
        priceLBL = new javax.swing.JLabel();
        urlLBL = new javax.swing.JLabel();
        typeLBL = new javax.swing.JLabel();
        modelLBL = new javax.swing.JLabel();
        numberLBL = new javax.swing.JLabel();
        makeLBL = new javax.swing.JLabel();
        colourLBL = new javax.swing.JLabel();
        sportLBL = new javax.swing.JLabel();
        brandLBL = new javax.swing.JLabel();
        urlTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        numberTF = new javax.swing.JTextField();
        typeTF = new javax.swing.JTextField();
        makeTF = new javax.swing.JTextField();
        modelTF = new javax.swing.JTextField();
        colourTF = new javax.swing.JTextField();
        sportTF = new javax.swing.JTextField();
        brandTF = new javax.swing.JTextField();
        displayBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        electricalRB = new javax.swing.JRadioButton();
        craftsuppliesRB = new javax.swing.JRadioButton();
        sportsRB = new javax.swing.JRadioButton();
        clearRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        descriptionLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        descriptionLBL.setText("Description:");

        priceLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        priceLBL.setText("Price");

        urlLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        urlLBL.setText("URL:");

        typeLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        typeLBL.setText("Type:");

        modelLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modelLBL.setText("Model:");

        numberLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numberLBL.setText("Number:");

        makeLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        makeLBL.setText("Make:");

        colourLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        colourLBL.setText("Colour:");

        sportLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sportLBL.setText("Sport:");

        brandLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brandLBL.setText("Brand:");

        urlTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTFActionPerformed(evt);
            }
        });

        typeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTFActionPerformed(evt);
            }
        });

        displayBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        searchBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        addBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        typeGrp.add(electricalRB);
        electricalRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        electricalRB.setText("Electrical");
        electricalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricalRBActionPerformed(evt);
            }
        });

        craftsuppliesRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        craftsuppliesRB.setText("Craft Supplies");
        craftsuppliesRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                craftsuppliesRBActionPerformed(evt);
            }
        });

        sportsRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sportsRB.setText("Sports Equipment");
        sportsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsRBActionPerformed(evt);
            }
        });

        typeGrp.add(clearRB);
        clearRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearRB.setText("Clear Selections");
        clearRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Click below for more choices");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urlLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(urlTF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descriptionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sportTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sportsRB)
                            .addComponent(craftsuppliesRB)
                            .addComponent(electricalRB)
                            .addComponent(clearRB)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(displayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(typeTF)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(electricalRB)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modelLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descriptionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(craftsuppliesRB)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sportsRB)
                            .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urlLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(brandLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(clearRB)
                        .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTFActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // 
            WishList2 m = new WishList2();
           m.setNumber(numberTF.getText());
            m.setDescription(descriptionTF.getText());
            m.setPrice(priceTF.getText());
            m.setUrl(urlTF.getText());
            m.setType(typeTF.getText());
            m.setMake(makeTF.getText());
            m.setModel(modelTF.getText());
            m.setBrand(brandTF.getText());
            m.setColour(colourTF.getText());
            m.setSport(sportTF.getText());
            WishLists.add(m);
       String item = numberTF.getText();
       File outFile;
       FileWriter fw;
       BufferedWriter bw;
       
       try{
           outFile = new File("WishList2.txt");
           fw = new FileWriter(outFile,true);
           bw = new BufferedWriter(fw);
           
           bw.write(item);
           bw.newLine();
           bw.close();
           JOptionPane.showMessageDialog(null, "Item added sucessfully");
       }
        catch(IOException e){
            System.out.println("Error writing to file: "+e);
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < WishLists.size(); i++) {
           WishList2 m =WishLists.get(i);
            JOptionPane.showMessageDialog(null, m.getDetails());
        }
       
       
        File inFile;
        FileReader fr;
        BufferedReader br;
        
        String item;
        try{
            inFile = new File("WishList2.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            item = br.readLine();
            while(item!=null){
                JOptionPane.showMessageDialog(null,"Item:"+item);
                item = br.readLine();
            }
            br.close();
        }
        catch(FileNotFoundException e){
            System.out.println(e);
        }
        catch(IOException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File("output.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(WishLists);
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
         if (WishLists.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no gift ideas to search for");
        } else {
            String searchTerm = JOptionPane.showInputDialog(null, "Enter a name to search for.");
            /* for(int i = 0; i < count;i++){
                if(employees.get(i).getId().equals(searchTerm)){
                    JOptionPane.showMessageDialog(null,employees[i].get(i).getDetails());
                }*/
            for (WishList2 m : WishLists) {
                if (m.getNumber().equals(searchTerm)) {
                    JOptionPane.showMessageDialog(null, m.getDetails());
                }
            }
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void electricalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricalRBActionPerformed
        // TODO add your handling code here:
        brandLBL.setVisible(false);
        brandTF.setVisible(false);
        colourLBL.setVisible(false);
        colourTF.setVisible(false);
        sportLBL.setVisible(false);
        sportTF.setVisible(false);
        typeLBL.setVisible(true);
        typeTF.setVisible(true);
        makeLBL.setVisible(true);
        makeTF.setVisible(true);
        modelLBL.setVisible(true);
        modelTF.setVisible(true);
        
    }//GEN-LAST:event_electricalRBActionPerformed

    private void craftsuppliesRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_craftsuppliesRBActionPerformed
        // TODO add your handling code here:
         brandLBL.setVisible(true);
        brandTF.setVisible(true);
        colourLBL.setVisible(true);
        colourTF.setVisible(true);
        sportLBL.setVisible(false);
        sportTF.setVisible(false);
        typeLBL.setVisible(true);
        typeTF.setVisible(true);
        makeLBL.setVisible(false);
        makeTF.setVisible(false);
        modelLBL.setVisible(false);
        modelTF.setVisible(false);
        
    }//GEN-LAST:event_craftsuppliesRBActionPerformed

    private void sportsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsRBActionPerformed
        // TODO add your handling code here:
          brandLBL.setVisible(true);
        brandTF.setVisible(true);
        colourLBL.setVisible(false);
        colourTF.setVisible(false);
        sportLBL.setVisible(true);
        sportTF.setVisible(true);
        typeLBL.setVisible(true);
        typeTF.setVisible(true);
        makeLBL.setVisible(false);
        makeTF.setVisible(false);
        modelLBL.setVisible(false);
        modelTF.setVisible(false);
    }//GEN-LAST:event_sportsRBActionPerformed

    private void urlTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTFActionPerformed

    private void clearRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRBActionPerformed
        // TODO add your handling code here:
         brandLBL.setVisible(false);
        brandTF.setVisible(false);
        colourLBL.setVisible(false);
        colourTF.setVisible(false);
        sportLBL.setVisible(false);
        sportTF.setVisible(false);
        typeLBL.setVisible(false);
        typeTF.setVisible(false);
        makeLBL.setVisible(false);
        makeTF.setVisible(false);
        modelLBL.setVisible(false);
        modelTF.setVisible(false);
    }//GEN-LAST:event_clearRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WishList2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WishList2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WishList2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WishList2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WishList2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel brandLBL;
    private javax.swing.JTextField brandTF;
    private javax.swing.JRadioButton clearRB;
    private javax.swing.JLabel colourLBL;
    private javax.swing.JTextField colourTF;
    private javax.swing.JRadioButton craftsuppliesRB;
    private javax.swing.JLabel descriptionLBL;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JButton displayBTN;
    private javax.swing.JRadioButton electricalRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel makeLBL;
    private javax.swing.JTextField makeTF;
    private javax.swing.JLabel modelLBL;
    private javax.swing.JTextField modelTF;
    private javax.swing.JLabel numberLBL;
    private javax.swing.JTextField numberTF;
    private javax.swing.JLabel priceLBL;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel sportLBL;
    private javax.swing.JTextField sportTF;
    private javax.swing.JRadioButton sportsRB;
    private javax.swing.ButtonGroup typeGrp;
    private javax.swing.JLabel typeLBL;
    private javax.swing.JTextField typeTF;
    private javax.swing.JLabel urlLBL;
    private javax.swing.JTextField urlTF;
    // End of variables declaration//GEN-END:variables
}
